# Generated by Django 3.2 on 2023-04-12 12:06

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingGroup',
            fields=[
                ('groupId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('committeeName', models.CharField(max_length=1000)),
                ('groupType', models.BooleanField(default=False)),
                ('isRecurring', models.BooleanField(default=True)),
                ('recurringTime', models.IntegerField(default=30)),
                ('groupMembers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('relatedDepartmentId', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('memberSecretary', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('meetingId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestampCreation', models.DateTimeField(max_length=50)),
                ('minutesOfMeeting', models.TextField(null=True)),
                ('minutesLink', models.CharField(default='', max_length=1000)),
                ('meetingSubject', models.CharField(max_length=1000)),
                ('scheduledTime', models.DateTimeField(max_length=50)),
                ('noticeLink', models.CharField(default='', max_length=1000)),
                ('doablesAssigned', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None)),
                ('agenda', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('documentId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentLink', models.CharField(max_length=1000)),
                ('uploadedBy', models.IntegerField()),
                ('meetingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
            ],
        ),
    ]
