# Generated by Django 3.0.4 on 2023-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calamitySen',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('dead', models.IntegerField(default=100)),
                ('injured', models.IntegerField(default=100)),
                ('peopleAffected', models.IntegerField(default=100)),
                ('cost', models.IntegerField(default=100)),
                ('police', models.IntegerField(default=100)),
                ('ambulance', models.IntegerField(default=100)),
                ('ndrfPersonnels', models.IntegerField(default=100)),
                ('lesson', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='crimeSen',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('location', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
                ('lesson', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='epidemicSen',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('infected', models.IntegerField(default=100)),
                ('cured', models.IntegerField(default=100)),
                ('died', models.IntegerField(default=100)),
                ('year', models.TextField(null=True)),
                ('hospitalBed', models.IntegerField(default=100)),
                ('healthStaff', models.IntegerField(default=100)),
                ('type', models.IntegerField(choices=[(1, 'Deadly'), (2, 'Infectious'), (3, 'Seasonal')], default=3)),
                ('lesson', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='publicGatheringSen',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('attendance', models.IntegerField(default=100)),
                ('police', models.IntegerField(default=100)),
                ('ambulance', models.IntegerField(default=100)),
                ('fireFighter', models.IntegerField(default=100)),
                ('location', models.TextField()),
                ('lesson', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='rallySen',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('attendance', models.IntegerField(default=100)),
                ('police', models.IntegerField(default=100)),
                ('ambulance', models.IntegerField(default=100)),
                ('fireFighter', models.IntegerField(default=100)),
                ('location', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Political'), (2, 'Social'), (3, 'Protest'), (4, 'Government'), (5, 'Religious')], default=3)),
                ('lesson', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
