# Generated by Django 3.2 on 2023-04-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20230411_1003'),
        ('sentenceSimilarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimesen',
            name='detailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.crime'),
        ),
        migrations.AlterField(
            model_name='epidemicsen',
            name='detailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.epidemic'),
        ),
        migrations.AlterField(
            model_name='publicgatheringsen',
            name='detailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.publicgathering'),
        ),
        migrations.AlterField(
            model_name='rallysen',
            name='detailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.rally'),
        ),
    ]
