# Generated by Django 3.2 on 2023-04-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20230411_1003'),
        ('sentenceSimilarity', '0002_auto_20230411_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemicsen',
            name='detailId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.calamity'),
        ),
    ]
