# Generated by Django 3.0.4 on 2023-02-12 04:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doable',
            fields=[
                ('doableId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('reminderPeriod', models.IntegerField(default=10)),
                ('assignedTo', models.IntegerField()),
                ('assignedBy', models.IntegerField()),
                ('subject', django.contrib.postgres.fields.jsonb.JSONField()),
                ('doableType', models.CharField(choices=[('compliance', 'Compliance'), ('meeting', 'Meeting')], default='meeting', max_length=20)),
                ('typeId', models.UUIDField(null=True)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
            ],
        ),
    ]
