# Generated by Django 3.2 on 2023-04-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicgathering',
            name='location',
            field=models.TextField(),
        ),
    ]
