# Generated by Django 3.2 on 2023-04-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_alter_publicgathering_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicgathering',
            old_name='lessons_learnt',
            new_name='lesson_learnt',
        ),
    ]
